"""Scrapes the 10 relevant Meta WhatsApp Flows doc pages into knowledge/meta_docs/.

Run manually (not part of the API):
    python scraper.py
"""

import asyncio
import os
import re
from pathlib import Path

from playwright.async_api import async_playwright

OUTPUT_DIR = Path(os.getenv("KNOWLEDGE_DIR", "/knowledge")) / "meta_docs"

URLS = {
    "flowjson": "https://developers.facebook.com/documentation/business-messaging/whatsapp/flows/reference/flowjson",
    "components": "https://developers.facebook.com/documentation/business-messaging/whatsapp/flows/reference/components",
    "media_upload": "https://developers.facebook.com/documentation/business-messaging/whatsapp/flows/reference/media_upload",
    "versioning": "https://developers.facebook.com/documentation/business-messaging/whatsapp/flows/reference/versioning",
    "error_codes": "https://developers.facebook.com/documentation/business-messaging/whatsapp/flows/reference/error-codes",
    "flow_endpoint": "https://developers.facebook.com/documentation/business-messaging/whatsapp/flows/guides/implementingyourflowendpoint",
    "example_loan": "https://developers.facebook.com/documentation/business-messaging/whatsapp/flows/gettingstarted/pre-approved-loan",
    "examples": "https://developers.facebook.com/documentation/business-messaging/whatsapp/flows/guides/examples",
    "best_practices": "https://developers.facebook.com/documentation/business-messaging/whatsapp/flows/guides/bestpractices",
    "testing_debugging": "https://developers.facebook.com/documentation/business-messaging/whatsapp/flows/guides/testingdebugging",
}

# elements that are navigation/noise
STRIP_SELECTORS = [
    "nav",
    "header",
    "footer",
    "[role='navigation']",
    "[class*='sidebar']",
    "[class*='Sidebar']",
    "[class*='breadcrumb']",
    "[class*='cookie']",
]
JUNK_LINES = {
    "Complete",
    "Proceed",
    "Read more",
    "Learn more",
    "Managed by the business.",
    "Preview Flow",
    "Select screen",
    "Preview",
    "Run",
    "Settings",
}


def clean_text(text: str) -> str:
    text = re.sub(
        r"\nPreview\nRun\nSettings\n.*?(?=\n##\s|\n###\s|\Z)",
        "\n",
        text,
        flags=re.DOTALL,
    )
    # drop residual preview UI lines
    text = "\n".join(
        line for line in text.splitlines() if line.strip() not in JUNK_LINES
    )
    text = re.sub(r"\n{3,}", "\n\n", text)
    text = "\n".join(line.rstrip() for line in text.splitlines())
    return text.strip()


async def scrape_page(page, name: str, url: str) -> str:
    await page.goto(url, wait_until="networkidle", timeout=60000)
    # give client-side rendering a moment
    await page.wait_for_timeout(3000)

    # remove noise elements
    for selector in STRIP_SELECTORS:
        await page.evaluate(f"""
            document.querySelectorAll("{selector}").forEach(el => el.remove());
        """)

    content = await page.evaluate("""
        () => {
            const main = document.querySelector("main") || document.body;
            const parts = [];

            const isPreviewNoise = (node) => {
                const text = (node.innerText || "").trim();
                // interactive preview panel UI chrome
                if (text === "Preview" || text === "Run" || text === "Settings"):
                    return true;
                if (text === "Preview Flow" || text === "Select screen"):
                    return true;
                if (text === "Managed by the business." || text === "Learn more"):
                    return true;
                // empty headers generated by preview panel
                if (node.tagName && node.tagName.match(/^H[1-4]$/) && text === ""):
                    return true;
                return false;
            };

            const walk = (node) => {
                for (const child of node.childNodes) {
                    if (child.nodeType !== 1) {  // not an element
                        continue;
                    }
                    if (isPreviewNoise(child)) continue;

                    const tag = child.tagName.toLowerCase();
                    if (tag === "h1" || tag === "h2") {
                        parts.push("\\n## " + child.innerText.trim() + "\\n");
                    } else if (tag === "h3" || tag === "h4") {
                        parts.push("\\n### " + child.innerText.trim() + "\\n");
                    } else if (tag === "pre" || tag === "code") {
                        parts.push("\\n```\\n" + child.innerText.trim() + "\\n```\\n");
                    } else if (
                                child.querySelector &&
                                child.querySelector("h1,h2,h3,h4,pre")
                            ) {
                        walk(child);  // descend into containers holding headers
                    } else {
                        const text = child.innerText ? child.innerText.trim() : "";
                        if (text) parts.push(text);
                    }
                }
            };
            walk(main);
            return parts.join("\\n");
        }
    """)
    return clean_text(content)


async def main():
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    async with async_playwright() as p:
        browser = await p.chromium.launch()
        page = await browser.new_page()

        for name, url in URLS.items():
            try:
                content = await scrape_page(page, name, url)
                if len(content) < 200:
                    continue
                out_file = OUTPUT_DIR / f"{name}.md"
                out_file.write_text(
                    f"# {name}\n\nSource: {url}\n\n{content}", encoding="utf-8"
                )
            except Exception:
                pass

        await browser.close()


if __name__ == "__main__":
    asyncio.run(main())
